<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-J9CEBMO" failures="1" tests="2" name="com.Framework.Test.Login" time="10.315" errors="1" timestamp="11 Apr 2025 06:07:50 GMT" skipped="0">
  <testcase classname="com.Framework.Test.Login" name="browser_Close" time="10.181">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;//div[@data-aura-class=&#039;forceEntityIcon&#039;]&quot;}
  (Session info: chrome=135.0.7049.84)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &#039;4.20.0&#039;, revision: &#039;866c76ca80&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;23.0.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [8e28aed9ce73359fc92f5156f9945b31, findElement {value=//div[@data-aura-class=&#039;forceEntityIcon&#039;], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 135.0.7049.84, chrome: {chromedriverVersion: 135.0.7049.84 (6c019e560019..., userDataDir: C:\Users\Dell\AppData\Local...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:52993}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:52993/devtoo..., se:cdpVersion: 135.0.7049.84, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 8e28aed9ce73359fc92f5156f9945b31" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-aura-class='forceEntityIcon']"}
  (Session info: chrome=135.0.7049.84)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [8e28aed9ce73359fc92f5156f9945b31, findElement {value=//div[@data-aura-class='forceEntityIcon'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 135.0.7049.84, chrome: {chromedriverVersion: 135.0.7049.84 (6c019e560019..., userDataDir: C:\Users\Dell\AppData\Local...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:52993}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:52993/devtoo..., se:cdpVersion: 135.0.7049.84, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 8e28aed9ce73359fc92f5156f9945b31
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:349)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at com.Framework.Test.HomePage.app_logOut(HomePage.java:24)
at com.Framework.GenericRepo.BaseClass.browser_Close(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- browser_Close -->
  <testcase classname="com.Framework.Test.Login" name="validLoginTest" time="0.134">
    <failure message="expected [https://ltt4-dev-ed.develop.lightning.force.com/lightning/setup/SetupOneHome/] but found [https://ltt4-dev-ed.develop.my.salesforce.com/_ui/identity/verification/method/SmsVerificationFinishUi/e?vcsrf=CQsWa1BII8i3o85y2o4mETRiohKBCMkYafGcRAn1ydyxQuOJxLsiIx7Ia7LCYx2s-celWYJN3UFkdTuv3QWTQm6QEW2VvQixduhiAjcT7nXsjAB_ssns5wTw4r7K6521XyaqXCCQBDktrm5dMJ9Xy3xkdqlM1Ca5JzL-k4pQdt4VVc0CZt34kKAzy4dppGpMai1mvK1JXu75yxyBS1C4l6Sew_WRg_P2lZPvKrUEsABZuOOFinYZYvdIIG8OPh7KcobhRlrBds7Rlu75Ywre0o_blDWCD3ilZqjRF60iQ2XE8nVFLQbskliGiT1P8goybNIY1BV0eTp6m_AI9r-9rAPEWUA0mvveX3dt7b1rkVPDd-XVkHdqI9nTnPxPAZZwTMGfAsJ1kAdDOWZs_iiUyWPqSa8ONDTDBlkq2ZPMa5Jrf0FP0lKl7svMPI6bDZKpd2lJbRIlc5Wz3fOqmtoNNlH2V828a9QfMa8HRjRS-BimDhcaNRTVabRbvqXDPp2ZRJl7djQMg150-A_ecU9cSQKPfD8NU3bVNC3tchyOHI9nb9zWdp-V-FBGW2te3cQ4c-wsSDffoDGPR6yoGze01LSG_nFkocg-IGjiKTEWvoi1R6luBUY95r74WzcBgdoktpwldfTUAJroqCMKHMJ2F27GF-Fr2RueVgTesL33JSo%3D&amp;vpol=ic&amp;vflid=0&amp;vfgrp=2024390417&amp;retURL=%2Fsecur%2Ffrontdoor.jsp%3Fallp%3D1%26cshc%3DR00000Fs4aJR0000007WIC%26apv%3D1%26display%3Dpage%26ucs%3D1]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://ltt4-dev-ed.develop.lightning.force.com/lightning/setup/SetupOneHome/] but found [https://ltt4-dev-ed.develop.my.salesforce.com/_ui/identity/verification/method/SmsVerificationFinishUi/e?vcsrf=CQsWa1BII8i3o85y2o4mETRiohKBCMkYafGcRAn1ydyxQuOJxLsiIx7Ia7LCYx2s-celWYJN3UFkdTuv3QWTQm6QEW2VvQixduhiAjcT7nXsjAB_ssns5wTw4r7K6521XyaqXCCQBDktrm5dMJ9Xy3xkdqlM1Ca5JzL-k4pQdt4VVc0CZt34kKAzy4dppGpMai1mvK1JXu75yxyBS1C4l6Sew_WRg_P2lZPvKrUEsABZuOOFinYZYvdIIG8OPh7KcobhRlrBds7Rlu75Ywre0o_blDWCD3ilZqjRF60iQ2XE8nVFLQbskliGiT1P8goybNIY1BV0eTp6m_AI9r-9rAPEWUA0mvveX3dt7b1rkVPDd-XVkHdqI9nTnPxPAZZwTMGfAsJ1kAdDOWZs_iiUyWPqSa8ONDTDBlkq2ZPMa5Jrf0FP0lKl7svMPI6bDZKpd2lJbRIlc5Wz3fOqmtoNNlH2V828a9QfMa8HRjRS-BimDhcaNRTVabRbvqXDPp2ZRJl7djQMg150-A_ecU9cSQKPfD8NU3bVNC3tchyOHI9nb9zWdp-V-FBGW2te3cQ4c-wsSDffoDGPR6yoGze01LSG_nFkocg-IGjiKTEWvoi1R6luBUY95r74WzcBgdoktpwldfTUAJroqCMKHMJ2F27GF-Fr2RueVgTesL33JSo%3D&vpol=ic&vflid=0&vfgrp=2024390417&retURL=%2Fsecur%2Ffrontdoor.jsp%3Fallp%3D1%26cshc%3DR00000Fs4aJR0000007WIC%26apv%3D1%26display%3Dpage%26ucs%3D1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.Framework.Test.Login.validLoginTest(Login.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- validLoginTest -->
</testsuite> <!-- com.Framework.Test.Login -->
